-dontwarn com.hua.abstractmusic.beean**
-keep class com.hua.abstractmusic.bean.** { *; }
-dontwarn com.yalantis.ucrop**
-keep class com.yalantis.ucrop** { *; }
-keep interface com.yalantis.ucrop** { *; }